version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: go_game_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: go_game
      POSTGRES_MAX_CONNECTIONS: 200
    ports:
      - "5433:5432"
    volumes:
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
