version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: go_game_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: go_game
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: